[package]
name = "my_redis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
hashbrown = "0.14.0"
tokio = { version = "1.28", features = ["full"] }
